steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - "--image=$_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - "--region=$_DEPLOY_REGION"
    id: Deploy
images:
  - "$_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
substitutions:
  _DEPLOY_REGION: us-west1
  _REPO_NAME: try-gcp
  _AR_HOSTNAME: us-west1-docker.pkg.dev
  _SERVICE_NAME: try-docker
options:
  logging: CLOUD_LOGGING_ONLY
